name: Reto04
on:
  workflow_dispatch:
jobs: 
 Job1:
   runs-on: ubuntu-latest
   steps:
     - name: step1
       run: echo 'hola'
     - name: step2
       run: echo 'STEP 2'}

 Job2:
   needs: Job1
   runs-on: ubuntu-latest
   steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
  
